export enum Configuration {
    PORT = 'PORT',
    GCLOUD_CREDENTIAL_B64 = 'GCLOUD_CREDENTIAL_B64',
    GCLOUD_PROJECT_ID = 'GCLOUD_PROJECT_ID',
    GCLOUD_TOPIC_NAME = 'GCLOUD_TOPIC_NAME',
    GCLOUD_SUBSCRIPTION_NAME = 'GCLOUD_SUBSCRIPTION_NAME'
}